In [3]:
import numpy as np

- Initialize input

In [4]:
b = -1
X = np.array([[0,0,b],[0,1,b],[1,0,b],[1,1,b]])
X

array([[ 0,  0, -1],
       [ 0,  1, -1],
       [ 1,  0, -1],
       [ 1,  1, -1]])

- Initialize weights for layer 1

In [5]:
w_l1 = np.array([[-0.5,0.5],[0.5,1],[0,-0.5]])
w_l1

array([[-0.5,  0.5],
       [ 0.5,  1. ],
       [ 0. , -0.5]])

- Dotting inputs with weights of layer 1

In [6]:
a1 = np.dot(X, w_l1)
a1

array([[ 0. ,  0.5],
       [ 0.5,  1.5],
       [-0.5,  1. ],
       [ 0. ,  2. ]])

Sigma function returns either 0 or 1

In [7]:
def sigma(x):
    return 0 if x <= 0 else 1

Perform sigma function on every element of dotted array

In [8]:
sigma_on_each = np.vectorize(sigma)
a1_sigma = sigma_on_each(a1)
a1_sigma

array([[0, 1],
       [1, 1],
       [0, 1],
       [0, 1]])

Initialize weights for layer 2

In [12]:
w_l2 = np.array([[1],[-1]])
w_l2

array([[ 1],
       [-1]])

Dot previous array with weights for layer 2

In [13]:
a2 = np.dot(a1_sigma, w_l2)
a2

array([[-1],
       [ 0],
       [-1],
       [-1]])

Perform sigma function on every element of new array

In [14]:
sum2_sigma = sigma_on_each(a2)
sum2_sigma

array([[0],
       [0],
       [0],
       [0]])

Initialize correct output y

In [16]:
y = np.array([[0],[1],[1],[0]])
y

array([[0],
       [1],
       [1],
       [0]])

Calculate final error for the neural network

In [19]:
error = sum2_sigma-y
error

array([[ 0],
       [-1],
       [-1],
       [ 0]])